//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Game
{
	public IEnumerable<Player> Players { get; set; }

    public Game(List<Player> players)
    {
        Players = players;
    }

	public void Play()
	{
		// TODO
	}

	public int ThrowDice()
	{
        int random = Random.
        
        return 0;
	}

	public void ChangeTurn()
	{
		// TODO
	}

}

