//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Game
{
	public virtual IEnumerable<Player> Player
	{
		get;
		set;
	}

	public virtual void Play()
	{
		throw new System.NotImplementedException();
	}

	public virtual int ThrowDice()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ChangeTurn()
	{
		throw new System.NotImplementedException();
	}

	private void InitGame()
	{
		throw new System.NotImplementedException();
	}

}

