//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Player
{
	public virtual string Name
	{
		get;
		set;
	}

	public virtual Color Color
	{
		get;
		set;
	}

    public Player(string name)
    {
        Name = name;
    }

	public virtual StartField StartField
	{
		get;
		set;
	}

	public virtual IEnumerable<Pawn> Pawn
	{
		get;
		set;
	}

	public virtual Pawn ChoosePawn()
	{
		throw new System.NotImplementedException();
	}

	public virtual void PlacePawn()
	{
		throw new System.NotImplementedException();
	}

}

