//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IField 
{
	IEnumerable<IField> IField { get;set; }

	void PlacePawn(Pawn pawn);

	void RemovePawn(Pawn pawn);

	bool CanPlace();

}

